### ISSUE TITLE
Paper "Untie the Knots: An Efficient Data Augmentation Strategy for Long-Context Pre-Training in Language Models"

### ISSUE THREAD

**Issue by rgtjf** [Xnhyacinth/Awesome-LLM-Long-Context-Modeling#11]
Thank you for maintaining this valuable repository! 

Could you please add the paper to the list?
- ArXiv: https://arxiv.org/abs/2409.04774
- GitHub: https://github.com/rgtjf/Untie-the-Knots

Thanks for your support!

**Comment by Xnhyacinth** [comment]
Sure, thanks for the excellent work, I will add this work in a future update

**Comment by Xnhyacinth** [comment]
It can be seen at https://github.com/Xnhyacinth/Awesome-LLM-Long-Context-Modeling/blob/f05a9eeab4b303c1dfa2f277a4141bff019b89e2/README.md?plain=1#L938

**Comment by rgtjf** [comment]
Thanks!
