### ISSUE TITLE
Would you consider adding A Controlled Study on Long Context Extension and Generalization in LLMs

### ISSUE THREAD

**Issue by NathanYanJing** [Xnhyacinth/Awesome-LLM-Long-Context-Modeling#12]
A Controlled Study on Long Context Extension and Generalization in LLMs
https://arxiv.org/pdf/2409.12181
video: https://www.youtube.com/watch?v=dc4chADushM

**Comment by Xnhyacinth** [comment]
Thanks for the issue, but it already exists in this repository and can be found at 94 of 11.1

**Comment by NathanYanJing** [comment]
ohh sorry my bad, and thanks!
