### ISSUE TITLE
Would you consider adding 'Sliding Windows Are Not the End: Exploring Full Ranking with Long-Context Large Language Models'?

### ISSUE THREAD

**Issue by 8421BCD** [Xnhyacinth/Awesome-LLM-Long-Context-Modeling#18]
Would you consider adding 'Sliding Windows Are Not the End: Exploring Full Ranking with Long-Context Large Language Models'?

**Comment by Xnhyacinth** [comment]
Sure. I'll add it in tomorrow's update. Thanks!
