### ISSUE TITLE
llama  2 long is missed.

### ISSUE THREAD

**Issue by kai-wen-yang** [Xnhyacinth/Awesome-LLM-Long-Context-Modeling#2]
Effective Long-Context Scaling of Foundation Models.

**Comment by Xnhyacinth** [comment]
Thanks for pointing out that the paper is missing. llama2 long is a very systematic work for an ultra-long context, carried out the model structure, training data, training method perspective for experimentation and analysis, and the output of a very much effective point of view. I have carefully studied, may be recorded in the process of forgetting, I will add today. Thanks again for pointing it out!

**Comment by Xnhyacinth** [comment]
> Thanks for pointing out that the paper is missing. llama2 long is a very systematic work for an ultra-long context, carried out the model structure, training data, training method perspective for experimentation and analysis, and the output of a very much effective point of view. I have carefully studied, may be recorded in the process of forgetting, I will add today. Thanks again for pointing it out!

You can see it here
[llama2 long](https://github.com/Xnhyacinth/Awesome-LLM-Long-Context-Modeling/blob/02a591cb667dec2ee8ea06f129bf856189f351c3/README.md?plain=1#L526)

**Comment by kai-wen-yang** [comment]
Thanks!
