### ISSUE TITLE
new survey paper

### ISSUE THREAD

**Issue by lastweek** [Xnhyacinth/Awesome-LLM-Long-Context-Modeling#6]
do you want to include this survey paper? https://arxiv.org/pdf/2405.11299

**Comment by Xnhyacinth** [comment]
Sure, I will add it today. Thanks a lot.



----- Original Message -----
From: "Yizhou Shan" ***@***.***>
To: Xnhyacinth/Awesome-LLM-Long-Context-Modeling ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Sat, 01 Jun 2024 18:26:22 -0700
Subject: [Xnhyacinth/Awesome-LLM-Long-Context-Modeling] new survey paper (Issue #6)



do you want to include this survey paper? https://arxiv.org/pdf/2405.11299

**Comment by Xnhyacinth** [comment]
I have added. [See here](https://github.com/Xnhyacinth/Awesome-LLM-Long-Context-Modeling/blob/617df67ac2e1a6f36e64d7c580bd17328918e6a3/README.md?plain=1#L192)
